repos:
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.26.0
    hooks:
      - id: pyproject-fmt
  # - repo: https://github.com/rhysd/actionlint
  #   rev: v1.7.12
  #   hooks:
  #     - id: actionlint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.39.9
    hooks:
      - id: basedpyright
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.39
    hooks:
      - id: pymarkdown
  - repo: local
    hooks:
      - id: pin-python-version
        name: generate .python-version
        entry: uv run scripts/pin_python_version.py
        language: system
        files: ^pyproject\.toml$
        pass_filenames: false