repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.39.10
    hooks:
      - id: basedpyright
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.39
    hooks:
      - id: pymarkdown
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.28.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: detect-private-key
  - repo: local
    hooks:
      - id: pin-python-version
        name: generate .python-version
        entry: uv run scripts/pin_python_version.py
        language: system
        files: ^pyproject\.toml$
        pass_filenames: false
