[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=80", "setuptools-scm[simple]>=9.2" ]

[project]
name = "beancount-daoru"
description = "beancount importers for Chinese"
readme = "README.md"
license = "MIT"
license-files = [ "LICENSE.txt" ]
authors = [ { name = "AN Qi", email = "aqnin@outlook.com" } ]
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "version" ]
dependencies = [
  "beangulp>=0.2,<0.3",
  "pdfplumber>=0.11.8",
  "pydantic>=2.12",
  "pyexcel>=0.7",
  "pyexcel-xls>=0.7.1",
  "pyexcel-xlsxr>=0.6.2",
  "typing-extensions>=4.15",
]
optional-dependencies.llm = [ "diskcache>=5.6.3", "openai>=2.11", "usearch>=2.21" ]
urls.repository = "https://github.com/aqni/beancount-daoru"

[dependency-groups]
dev = [
  "debugpy>=1.8.18",
  "gitpython>=3.1",
  "prek>=0.4.12",
  "pytest>=9",
  "pytest-cov>=7",
  "vcrpy>=8.3",
]

[tool.ruff]
lint.extend-select = [ "ALL" ]
lint.extend-ignore = [ "COM812", "CPY001" ]
lint.per-file-ignores."examples/*" = [ "D", "INP001" ]
lint.per-file-ignores."scripts/*" = [ "D", "INP001" ]
lint.per-file-ignores."tests/*" = [ "D", "RUF001", "S101", "S603" ]
lint.pydocstyle.convention = "google"

[tool.pytest]
ini_options.testpaths = [ "tests" ]
ini_options.addopts = "--cov=src/ --cov-branch"
ini_options.disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true

[tool.basedpyright]
allowedUntypedLibraries = [
  "beangulp",
  "diskcache",
  "xprocess",
  "pyexcel",
  "usearch",
  "vcr",
]
