name: "setup llama.cpp"
description: "setup llama.cpp"
inputs:
    version:
        description: "llama.cpp version, blank for latest"
        required: false

runs:
    using: "composite"
    steps:
        - name: Setup mongodb into Runner Tool Cache
          uses: pbrisbin/setup-tool-action@v2
          with:
              name: llama
              version: ${{ inputs.version }}
              url: "https://github.com/ggml-org/llama.cpp/releases/download/{version}/{name}-{version}-bin-{os}-{arch}.{ext}"
              os-win32: win-cpu
              os-linux: ubuntu
              os-darwin: macos
              subdir: "{name}-{version}"
              subdir-win32:
