name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate-pr-title:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-lock-file:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv lock --check

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        command:
          - pymarkdown scan -r --respect-gitignore .
          - ruff check --verbose
          - ruff format --check --diff --verbose
          - basedpyright --verbose src
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv run --frozen --no-dev --all-extras --group lint ${{ matrix.command }}

  test:
    needs:
      - validate-pr-title
      - check-lock-file
      - lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
      - name: Setup llama.cpp to PATH
        uses: pbrisbin/setup-tool-action@v2
        with:
          name: llama
          url: "https://github.com/ggml-org/llama.cpp/releases/download/{version}/{name}-{version}-bin-{os}-{arch}.{ext}"
          os-win32: win-cpu
          os-linux: ubuntu
          os-darwin: macos
          subdir-linux: "{name}-{version}"
          subdir-darwin: "{name}-{version}"
      - name: Run All Tests
        run: uv run --frozen --no-dev --all-extras --group test pytest --verbose
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

  report:
    if: always()
    needs:
      - validate-pr-title
      - check-lock-file
      - lint
      - test
    runs-on: ubuntu-slim
    steps:
    - uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
