name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate-pr-title:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
      - uses: astral-sh/setup-uv@v7
      - name: pre-commit
        run: uv run --locked --all-extras prek run --all-files --verbose

  test:
    needs:
      - validate-pr-title
      - pre-commit
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
      - uses: astral-sh/setup-uv@v7
      - name: pytest
        run: uv run --frozen --all-extras pytest --verbose

  report:
    if: always()
    needs:
      - validate-pr-title
      - pre-commit
      - test
    runs-on: ubuntu-slim
    steps:
    - uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

  automerge:
    needs: report
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: true
